### ISSUE TITLE
CT Build failed with status code

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#616] opened 2024-03-11 21:21 UTC
```
center-and-variability : build
Build failed with status code 1:
Running "report-media" task
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player01Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player01PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player01Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player02Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player02PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player02Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player03Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player03PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player03Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player04Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player04PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player04Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player07Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player07PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player07Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player11Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player11PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player11Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player13Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player13PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/player13Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer01Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer01PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer01Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer02Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer02PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer02Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer03Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer03PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer03Standing.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer04Kicking.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer04PoisedToKick.svg
>> not-annotated: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1710186582771/soccer-common/images/africa/variabilityPlayer04Standing.svg
Fatal error: There is an issue with the licenses for media types.
Snapshot from 3/11/2024, 1:49:42 PM

----------------------------------

center-and-variability : migration : 1.1->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/phet-io-wrappers/migration/?sim=center-and-variability&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D
Assertion failed: MigrationReport problem: missingStringPhetioElements

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.africaModestStringProperty",
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.africaStringProperty",
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.unitedStatesOfAmericaStringProperty"
]
}
[object Object]
Error: Assertion failed: MigrationReport problem: missingStringPhetioElements
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/assert/js/assert.js:28:13)
at assert (MigrationReport.ts:164:22)
at reportForContext (MigrationEngine.ts:86:22)
at migrate (StandardPhetioWrapper.ts:281:37)
at async (http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/phet-io-wrappers/migration/migration.js:220:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1710186582771%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dcenter-and-variability%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1710186582771%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dcenter-and-variability%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/phet-io-wrappers/migration/?sim=center-and-variability&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D
[ATTACHED]
[NAVIGATED] about:blank
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/studio/?sim=center-and-variability&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D&phetioMigrationReport=assert&fuzz&locales=*
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/center-and-variability/center-and-variability_en.html?brand=phet-io&ea&postMessageOnError&sim=center-and-variability&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/center-and-variability/1.1/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[CONSOLE] enabling assert
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710186582771%22%2C%22timestamp%22%3A1710187280906%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: MigrationReport problem: missingStringPhetioElements

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.africaModestStringProperty",
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.africaStringProperty",
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.unitedStatesOfAmericaStringProperty"
]
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: missingStringPhetioElements

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.africaModestStringProperty",
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.africaStringProperty",
"centerAndVariability.general.model.strings.joist.preferences.tabs.localization.regionAndCulture.portrayalSets.unitedStatesOfAmericaStringProperty"
]
}
[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/assert/js/assert.js:28:13)
at MigrationReport.reportForContext (http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:141:23)
at MigrationEngine.migrate (http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationEngine.js:65:23)
at StandardPhetioWrapper.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/chipper/dist/js/phet-io-wrappers/common/js/StandardPhetioWrapper.js:199:38)
at async http://128.138.93.172/continuous-testing/ct-snapshots/1710186582771/phet-io-wrappers/migration/migration.js:220:11
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 3/11/2024, 1:49:42 PM
```

**Comment by samreid** [comment] 2024-03-12 01:12
Some of the messages indicate regionAndCulture, so I'll defer to @marlitas

**Comment by pixelzoom** [comment] 2024-03-12 23:55
This occurred on 3 CT cycles yesterday.  It was caused by svg files that @amanda-phet checked in without updating license.json, and with no commit messages - see https://github.com/phetsims/soccer-common/commit/1513f6a083aaf767caae4f7a6664640b2d471f5a.  I deleted those files in https://github.com/phetsims/soccer-common/commit/33e56998e7be2e45851176003f0da33ee2feb617.

Closing.

**Closed by pixelzoom** 2024-03-12 23:55 UTC
Labels: type:automated-testing
