### ISSUE TITLE
Delay when opening the Variability screen for the first time

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#527] opened 2023-09-02 13:49 UTC
For https://github.com/phetsims/qa/issues/976, I am seeing a delay when I switch to the Variability screen. 
With Chrome (tested with Mac, Dell and Chromebook), the delay only occurs the first time I switch to that screen. 
With safari (tested on the Mac and iPad), the delay is shorter but it occurs every time I switch to that screen. 

Here is a video using the chromebook (watch with sound on):

https://github.com/phetsims/center-and-variability/assets/87318828/b6f1ba8d-f848-43f3-9632-20550802d7c8

and here it is on my mac with safari (no sound but look at the mouse click):

https://github.com/phetsims/center-and-variability/assets/87318828/45cea572-0b17-439a-8034-b64b23d02a26

**Comment by marlitas** [comment] 2023-09-06 20:13
I ran a performance log switching to the variability screen and it is indeed getting clogged up. However, I'm not sure how to read these and I have never really had to debug performance issues like this before so I will need help from another dev...

![image](https://github.com/phetsims/center-and-variability/assets/42476338/f9e3deba-5215-44c3-b85f-07ea44568aca)

**Comment by pixelzoom** [comment] 2023-09-08 19:20
Reproduced on macOS + 13.4.1 with Safari 16.5.1 and Chrome 116.

**Comment by pixelzoom** [comment] 2023-09-08 19:26
To confirm that the delay is really related to the Variability screen, I tried changing the order and number of screens with (for example) `?screen=3,2,1` and `?screens=3,1`.   The delay occurred only with the Variability screen in all cases.

**Comment by pixelzoom** [comment] 2023-09-08 19:35
I don't see any deferred initialization related to the Variability screen.

Poking around in Studio, the Variability screen has a lot more elements. Perhaps the delay is due to the fact that the Variability screen is significantly bigger (more associated code) than the other 2 screens. It has 4 scenes, each of which includes an instance of `VariabilitySceneModel` and `CAVSceneView`.

**Comment by pixelzoom** [comment] 2023-09-08 19:45
My hypothesis is that the delay is due to the fact that the Variability screen has 4 scenes, while the other screens have 1 scene.  I attempted to test that hypothesis by reducing the number of scenes to 1 for the Variabilty screen.  But that is unfortuantely not possible, see #545.

**Comment by pixelzoom** [comment] 2023-09-08 20:29
I also tried increasing the number of scenes for the Variability screen , to see if the delay would increase. Again I ran into problems with the implementation being dependent on having exactly 4 scenes, see #545.

**Comment by pixelzoom** [comment] 2023-09-08 20:45
Hacking my way through #545 to eliminate the dependency on "exactly 4 scenes", I was finally able to reduce the number of scenes to 1 for the Variability screen.  (You can find a patch in https://github.com/phetsims/center-and-variability/issues/545#issuecomment-1712200815, if you'd like to test yourself.)  With 1 scene, the Variability screen loads just as quickly as the other 2 screens.  

So... I'm not sure what can be done about this. You may need to live with it.

**Comment by marlitas** [comment] 2023-09-08 22:00
> I'm not sure what can be done about this. You may need to live with it.

Hmmm I was worried about this. Do you know what the performance impact of ToggleNodes is? I know we use quite a few and I wonder if reducing may help us here and toggle visibility of nodes ourselves.... That already sounds like it won't be any better.

This would be a large architectural change, and I'm not sure if it would be worth it, but perhaps instead of drawing 4 versions of all the different data points and their places in the plot we just move them around according to which model is visible... We would still have one plot node for each variability measure type. This means we would have 3 different plot nodes (Range, IQR, and MAD), with a maximum of 30 data points each. This would reduce the number of data points that need to be drawn by 540. 270 for the plot nodes in the accordion box and 270 for the plot nodes in the info dialog.

It would be good to talk this through with other devs to get a better sense of what the priority for this performance improvement is.

**Comment by marlitas** [comment] 2023-09-11 23:00
This is ready for code review as well as QA check-in.

@Nancy-Salpepi, all relevant changes should be pushed up to main now.

**Comment by Nancy-Salpepi** [comment] 2023-09-11 23:46
Looks much better on main! I tested with mac, iPad and Chromebook.

**Comment by matthew-blackman** [comment] 2023-09-18 20:56
@marlitas and I reviewed this with @samreid and @pixelzoom, and concluded that the changes to ToggleNode are worth keeping in common code. They are relatively lightweight and add opt-in functionality for removing invisible children from the scene graph.

Although the performance problems in this issue have been fixed by the changes in https://github.com/phetsims/center-and-variability/issues/530, @marlitas @samreid and I noticed some performance improvements on loading the Variability screen with the new feature of ToggleNode.

**Closed by matthew-blackman** 2023-09-18 20:56 UTC
Labels: dev:help-wanted, status:ready-for-review, type:performance
