### ISSUE TITLE
CT: leftmostCard should be defined

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#358] opened 2023-07-11 16:46 UTC
Coming from commits in https://github.com/phetsims/center-and-variability/issues/317

```
center-and-variability : multitouch-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1689087639543/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1689087639543%22%2C%22timestamp%22%3A1689087903154%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Uncaught Error: Assertion failed: leftmostCard should be defined
Error: Assertion failed: leftmostCard should be defined
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1689087639543/assert/js/assert.js:28:13)
at assert (CardNodeContainer.ts:129:24)
at callback (AsyncCounter.ts:31:11)
at increment (CardNodeContainer.ts:178:69)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
at emit (Animation.ts:322:24)
at listener (TinyEmitter.ts:122:8)
at emit (Sim.ts:413:16)
at apply (PhetioAction.ts:161:16)
id: Sparky Puppeteer
Snapshot from 7/11/2023, 9:00:39 AM
```

**Comment by marlitas** [comment] 2023-07-11 16:47
This is the problematic commit:

https://github.com/phetsims/center-and-variability/commit/6a726d8e4e7be170d80d010595361926333b55a8

**Comment by matthew-blackman** [comment] 2023-07-11 18:52
The commit above seems to have stopped this error. @marlitas and think the problem is that asyncCounter is occasionally firing after cards have been erased/reset because of the animationEnded persisting.  We weren't totally sure that this guard is the best way to solve this, but it appears to be working. Over to you for review @samreid

**Comment by samreid** [comment] 2023-07-17 17:46
@matthew-blackman and I reviewed it, and decided to make AsyncCounter more graceful, then we could remove the extraneous guard altogether.  Closing.

**Closed by samreid** 2023-07-17 17:46 UTC
Labels: status:ready-for-review, type:automated-testing
