### ISSUE TITLE
Frozen sim after picking up empty card

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#592] opened 2023-10-23 20:57 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/999
It is possible to freeze the sim by trying to pick up a card when one isn't there, then trying to kick a ball.
**Steps to reproduce**
1. On the first screen, use keyboard nav to focus on the card area
2. Use space as if picking up a card
3. The prompt to press space to pick up a card will show up
4. Press kick five

**Visuals**

https://github.com/phetsims/center-and-variability/assets/41024075/959e1fe7-f157-4469-83cf-21158ef2e6c5

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.1.0-rc.3/phet/center-and-variability_all_phet.html
Version: 1.1.0-rc.3 2023-10-22 23:55:32 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment] 2023-10-24 17:10
This was a straightforward fix. No code review needed. Ready for cherry pick.

**Comment by Nancy-Salpepi** [comment] 2023-10-27 15:49
I'm unable to reproduce this in rc.4. Closing.

**Closed by Nancy-Salpepi** 2023-10-27 15:49 UTC
Labels: type:bug, status:ready-for-review
