### ISSUE TITLE
Launching while kicks occur lead to wrong number of results

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#83] opened 2022-03-07 23:35 UTC
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/781.  In studio, if you launch the sim while kicks are occurring, the resulting sim will not have the correct number of balls launched and no option left to kick.
**Steps to Reproduce**
1. In studio, go to the first screen
2. Press the kick 5 button three times
3. Launch the sim

**Visuals**
![unkick](https://user-images.githubusercontent.com/41024075/157135821-e87d34c7-a5cc-41bf-8935-2fbe9281563c.gif)

**Comment by amanda-phet** [comment] 2022-03-11 18:34
This is not a priority for the classroom prototype because we can ensure that we don't launch the sim mid-kick.

**Comment by amanda-phet** [comment] 2022-03-16 22:47
@chrisklus says this might be fixed, and if so, that's great! Adding to the milestone for @samreid and @chrisklus 's attention.

**Comment by samreid** [comment] 2022-03-18 17:08
We confirmed this is fixed, closing.

**Closed by samreid** 2022-03-18 17:08 UTC
Labels: type:bug
