### ISSUE TITLE
Add soccer ball count to all screens

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#272] opened 2023-06-16 17:01 UTC
After interviews, having the knowledge of how many balls are in the playing area seemed useful since the participants continually counted the balls after each button press for kicking.

Let's put this under the checkbox group on the right side for the play area, left aligned with the checkboxes:

![image](https://github.com/phetsims/center-and-variability/assets/109630002/d24f69dd-5e12-4c0f-b29d-77caae4dce65)
![image](https://github.com/phetsims/center-and-variability/assets/109630002/482308cd-6458-4f5b-b241-93825f804625)

**Comment by catherinecarter** [comment] 2023-06-16 18:25
Also, the handles from the interval tool icon can be removed as to not clutter the space over in that area. Please make the icon match in size with the range, IQR, and MAD icons currently in the accordion box.

**Comment by samreid** [comment] 2023-06-16 20:24
@marlitas want to take the lead on this?

**Comment by marlitas** [comment] 2023-06-20 22:44
Okay this is ready for review! Over to you @catherinecarter 

<img width="222" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/0c54006e-024c-466c-bda5-07039b6adbc6">

Please keep in mind that I opened a separate issue to address consistent sizing between icons, since that will probably be more of a back and forth. https://github.com/phetsims/center-and-variability/issues/292

**Comment by catherinecarter** [comment] 2023-06-21 17:01
I think it looks great.

**Comment by marlitas** [comment] 2023-06-21 17:21
Added to all screens and ready for code review.

**Comment by samreid** [comment] 2023-06-22 13:35
I'm planning to review this one, thanks!

**Comment by samreid** [comment] 2023-06-22 14:02
I read through all the commits related to the kicks readout, and everything seems good. I tested in a variety of circumstances, and confirmed the number only changes when the ball reaches the top of the stack.  Everything seems great and I don't have any recommendations.  Thanks! Closing.

**Closed by samreid** 2023-06-22 14:02 UTC
Labels: dev:enhancement, status:ready-for-review
