### ISSUE TITLE
Update info boxes to remove title and instead, bold vocab work in definition

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#276] opened 2023-06-16 17:53 UTC
After design meeting 06.15.23, we decide the info boxes were redundant in the number of times the vocab word appeared. In all info boxes, we are removing the stand-alone title and instead bolding the first word/phrase in the definition. 

Range: 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/75396368-2fd4-4367-ad8b-739c5011cf9f)

IQR: 
![image](https://github.com/phetsims/center-and-variability/assets/109630002/f69c136e-a193-4a5f-9b95-d1f6068d1f91)

MAD:
![image](https://github.com/phetsims/center-and-variability/assets/109630002/2e6f1241-13e0-46ab-a229-8e6bf4c16117)

**Comment by samreid** [comment] 2023-06-20 15:55
@catherinecarter said this looks good, and she will open a side issue about spacing.  Next up: code review

**Comment by marlitas** [comment] 2023-06-20 16:50
I went ahead and addressed the spacing with @catherinecarter and @matthew-blackman post stand-up meeting. There was also a note that we wanted to change "Values:" to "Data Values:" across all screens. I implemented that change as well. Next up is reviewing the code commits done prior.

**Comment by marlitas** [comment] 2023-06-20 16:53
Commit looks good @samreid, but I am seeing a lot of duplication in options across the infoNodes... I wonder if it would be best to abstract those options out into a constant, or create a base class... there's a very repeatable pattern happening across all infoNodes.

**Comment by samreid** [comment] 2023-06-20 23:15
I factored out InfoTitleDescriptionRichText.ts.  Anything else duplicated that would be good to factor out?

**Comment by matthew-blackman** [comment] 2023-06-21 17:18
In investigating the title text with @catherinecarter, she noted that the title of the MAD info box looks smaller. In testing, we confirmed that the title text in the MAD info node was being shrunk due to the max width of the accordion box. @marlitas and I feel this can be solved by increasing the max width of the accordion box.

**Comment by marlitas** [comment] 2023-06-21 17:30
The maxTextWidth has been increased in the above commit, and everything else looks good to go. Closing.

**Closed by marlitas** 2023-06-21 17:30 UTC
