### ISSUE TITLE
Interval tool is no longer translatable from play area

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#506] opened 2023-08-22 17:13 UTC
The interval tool is currently draggable as a whole from the accordion box but not from the play area. The translation should be able to also translate from the soccer field play area as well.

**Comment by samreid** [comment] 2023-08-23 01:09
The problem is that CAVScreenView.ts has:

```ts
    this.backScreenViewLayer = new Node( {
      children: [
        new BackgroundNode( GROUND_POSITION_Y, this.visibleBoundsProperty ),

        // median highlight appears in front of the ticks, so these need to be in the background.
        this.playAreaNumberLineNode,

        this.intervalToolLayer,
        backLayerToggleNode
      ]
    } );
```

That is, the interval tool layer is behind the backLayerToggleNode.  That contains the SoccerSceneView.ts part:

```ts
    // Keep soccer balls in one layer, so we can control the focus order.
    const backLayerSoccerBallLayer = new InteractiveHighlightingNode( {
      children: [ this.highlightRectangle ],
      focusable: true,
      tagName: 'div'
    } );
```

in https://github.com/phetsims/center-and-variability/issues/406 the highlightRectangle was added, which is a Path. I can make the Path non-pickable but then that flickering comes back. Maybe we will need to move that highlight rectangle behind the interval tool so it doesn't intercept events?  @marlitas what do you think?

**Comment by samreid** [comment] 2023-08-23 19:44
We discussed the problem and would like to reach out to @jessegreenberg for help. The problem seems to be a z-ordering problem. The interval tool has to be in the back (for visual look, and so the user can access the soccer balls), but the rectangle that gets rid of the flickering for the soccer balls is in front. We suspect but aren't sure that the soccer ball input area has to travel with the soccer ball layer.

**Comment by jessegreenberg** [comment] 2023-08-23 20:35
Yes, I think to get this to work you might need to change the z-order to be 
- Hit rectangle for the group highlight (So that input falls back to this Node)
- Interval tool (So that this can receive input on top of the hit rectangle)
- Rest of the soccer scene view (For visual look)

But to be honest, I would recommend getting rid of this hit rectangle altogether. It creates the illusion that the background is interactive when it is not. The space is large enough that flickering is not an issue IMO (as it was for the cards). And I think it could be confusing that there is a highlight when no balls are present. So I think the interactive components would be more accessible without it. Let me know if I can help further!

**Comment by marlitas** [comment] 2023-08-23 21:08
@jessegreenberg Thanks for the quick response! 

This is the difficulty we ran into:
- the layer that contains the soccer balls and group highlight must be in front of the interval tool.
- the highlight rectangle that controls group highlight must be behind the interval tool.

We were unsure how Interactive highlight would function properly when the highlightRectangle cannot be a child of the node that is controlling group highlight?

> But to be honest, I would recommend getting rid of this hit rectangle altogether. It creates the illusion that the background is interactive when it is not. 

I agree, and this is a question that should be answered by @catherinecarter and @terracoda. This would create flickering between ball stacks, but I agree it is not as jarring as the flickering that was occurring with the cards.  Assigning over to them for conversation.

**Comment by catherinecarter** [comment] 2023-08-24 15:57
While the flickering is distracting, this seems like a good solution since we don't want the interval tool to be in front of the soccer balls. Good from my end.

**Comment by phet-dev** [comment] 2023-08-25 09:26
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment] 2023-08-25 14:50
Fixed, thanks @phet-dev, closing.

**Closed by samreid** 2023-08-25 14:50 UTC
Labels: status:ready-for-review
