### ISSUE TITLE
Panning is odd when moving Interval Tool with alt input while zoomed in

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#564] opened 2023-09-27 22:12 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.2

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/985, on the Variability Screen if I move the interval tool with alt input while zoomed in the screen pans up and then left/right. This doesn't allow me to see the field at all. Even if I pan down, as soon as I move the tool again, the screen pans back up to the panel. 

@jessegreenberg and I weren't sure what the desired behavior was. @catherinecarter wondering how you want panning to work here? 

**Steps to reproduce**
1. On the Variability Screen, toggle the Interval Tool on
2. Zoom in
3. Tab to the interval tool and begin to move it left and right (translation)
4. Use your mouse to pan down and then use the arrow keys to move the interval tool again. 

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/d8aa8bb9-21eb-4360-9593-2cacc92c6bde

**Comment by jessegreenberg** [comment] 2023-09-27 22:20
Yes, the default behavior for pan/zoom is to move the screen so that the center of the focused object is in the center of the viewport, and we haven't really had to deviate from that before.

A simple change could be to make the screen pan downward so that the field is always in view.

But @Nancy-Salpepi had a good suggestion:

> if I move the up/down arrows it should pan up and down so I can choose which thing I want to see--the panel or the field. And the left/right arrows just move it left and right.

I think that is a common code change that we could make quickly.

**Comment by catherinecarter** [comment] 2023-09-27 22:27
Seems natural to have the zoomed portion of the screen stay closer to the field since the accordion box markers are not interactive. 

Having the focus change to be on the accordion box might make sense if that's where your eyes were focused, but from your video, it looks like you were focused on the field and having to pan back down to the field is not the desired behavior. 

I played with it, and it looks like the focus is centering vertically on the tool when there's focus on it. When something moves, the focus goes back to vertically centering on the tool, but only when I press my arrow the second time. The first time I moved it, it stayed on the field.

The desired behavior seems like if the focus is on the field when engaged with translating the tool left/right, the focus should remain on the field.

Does that help?

**Comment by marlitas** [comment] 2023-09-27 23:01
@catherinecarter how do you feel about @Nancy-Salpepi's recommendation? "if I move the up/down arrows it should pan up and down so I can choose which thing I want to see--the panel or the field. And the left/right arrows just move it left and right."

This seems like a reasonable UX to me. I worry about forcing focus to stay on the field for example if someone specifically was using the tool in the accordion box.

**Comment by catherinecarter** [comment] 2023-09-28 14:47
@marlitas, yes, I completely agree with the UX @Nancy-Salpepi described. 

Just to confirm, since the accordion box has no interactive components on the graph, the user would select the checkbox, tab to each handle then the tool, pan up, then move right/left to put the tool where they wanted on the accordion box graph? 

That seems like the ideal situation, yes.

**Comment by jessegreenberg** [comment] 2023-09-28 19:49
OK! So we want the left/right arrow keys to translate the tool while the up/down arrow keys are free to pan the sim. Unfortunately, AccessibleSlider must use all arrow keys. So I think this is roughly the path to accomplish this:

1) Replace AccessibleSlider with a KeyboardListener or a KeyboardDragListener in IntervalToolRectangle.ts that responds to only the left/right arrow keys.
2) Add support in scenery to say "only pan vertically/horizontally please". I am not sure the best way to support that yet, but I don't think that will be too difficult and might be supported already with existing APIs.

However, I can't work on this issue again until after Monday 10/2. @marlitas what are your thoughts about 1? We would lose home/end/page up/page down keys unless we re-implement them with a KeyboardListener. How important is it that this component has AccessibleSlider functionality?

**Comment by marlitas** [comment] 2023-09-28 22:49
> Replace AccessibleSlider with a KeyboardListener or a KeyboardDragListener in IntervalToolRectangle.ts that responds to only the left/right arrow keys.

Ahh this makes sense and is definitely a bummer. I think the importance of that slider functionality with the IntervalTool is more of a @catherinecarter question. It will be kind of a bummer to lose that built in AccessibleSlider functionality, and that it's interaction no longer matches any of the other prediction tools, but it is different enough from the other tools that it probably won't be too jarring.

Porting it to a KeyboardDragListener otherwise should be fine. 

Another question I have is wether we want to port the entire IntervalTool (including handles), or just the IntervalToolRectangle? I'm guessing this would mean that if you are focused on the handles, pan/zoom will move there no matter what. 

This might be a good issue to discuss synchronously. I'll label it as such.

**Comment by jessegreenberg** [comment] 2023-09-29 16:37
We *could* look into changing AccessibleSlider to optionally only use left/right arrow keys. @terracoda do you have any concerns with that? Like would that make screen reader accessibility more difficult in the future?

**Comment by marlitas** [comment] 2023-09-29 18:58
@jessegreenberg, the CAV team met today and had this question that may be a bit easier to implement?

In this code in `AnimatedPanZoomListener` we were wondering if there would be a way we could override the `y` for the IntervalToolRectangle only, so that it does not auto pan in the `y` direction when focus is on that node.

```js
if ( distanceToBottomEdge < 0 ) {
      translationDelta.y = -distanceToBottomEdge;
    }
    if ( distanceToTopEdge > 0 ) {
      translationDelta.y = -distanceToTopEdge;
    }
```

**Comment by jessegreenberg** [comment] 2023-09-29 19:14
Yes, I think that is the idea! We would need to think of an API for that though. I am guessing adding a field to Node so that the listener knows to change behavior for IntervalToolRectangle specifically. But there is already some support for setting custom bounds that would stay in view instead of the target Node, I am wondering if we can use that. There is also an initial pan that happens on focus that we want to avoid in this case.

**Comment by marlitas** [comment] 2023-09-29 20:38
@jessegreenberg, okay great! We determined that this feels like this fix is worth 1 to 2 hours of work. If it's much more than that then we think it's not worth the effort to address for this sim. Let me know how that feels, and if you'd like to meet to talk through any of it!

**Comment by terracoda** [comment] 2023-09-30 16:47
I am not sure what is the issue being discussed here, but regarding comment 
https://github.com/phetsims/center-and-variability/issues/564#issuecomment-1741188780

Sliders have an orientation and when that orientation is specifically communicated blind learners would generally expect to use up and down arrows for vertical sliders and left and right arrows for horizontal sliders.

When orientation is not explicitly communicated it is unclear to blind user which arrow keys would be tried out as an intuitive guess.

**Comment by terracoda** [comment] 2023-09-30 16:50
And default orientation if unspecified is horizontal, I do believe. 

When exactly (how often exactly) orientation is read out may vary among screen reader software and user specific screen reader settings.

**Comment by marlitas** [comment] 2023-10-04 17:53
@jessegreenberg  and I discussed the proposed solution by the CAV team, and JG felt that the below patch (pseudocode) is a start to that solution. He believes this will take about half an hour and be relatively low risk.

<details>

```diff
Subject: [PATCH] panDirection
---
Index: js/accessibility/pdom/ParallelDOM.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/accessibility/pdom/ParallelDOM.ts b/js/accessibility/pdom/ParallelDOM.ts
--- a/js/accessibility/pdom/ParallelDOM.ts	(revision 794ad610b51dfe8d31c023d0758a135a37c5e1cd)
+++ b/js/accessibility/pdom/ParallelDOM.ts	(date 1696441929710)
@@ -231,6 +231,7 @@
   'activeDescendantAssociations',
 
   'createPanTargetBounds',
+  'focusPanDirection', // could take values of: 'vertical', 'horizontal', 'both'
 
   'positionInPDOM',
 
Index: js/listeners/AnimatedPanZoomListener.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/listeners/AnimatedPanZoomListener.ts b/js/listeners/AnimatedPanZoomListener.ts
--- a/js/listeners/AnimatedPanZoomListener.ts	(revision 794ad610b51dfe8d31c023d0758a135a37c5e1cd)
+++ b/js/listeners/AnimatedPanZoomListener.ts	(date 1696441929716)
@@ -924,13 +924,13 @@
       distanceToTopEdge = this._transformedPanBounds.top - boundsInTargetFrame.top;
       distanceToBottomEdge = this._transformedPanBounds.bottom - boundsInTargetFrame.bottom;
     }
-
-    if ( distanceToBottomEdge < 0 ) {
-      translationDelta.y = -distanceToBottomEdge;
-    }
-    if ( distanceToTopEdge > 0 ) {
-      translationDelta.y = -distanceToTopEdge;
-    }
+    FocusManager.pdomFocusProperty.value.focusPanDirection;
+    // if ( distanceToBottomEdge < 0 ) {
+    //   translationDelta.y = -distanceToBottomEdge;
+    // }
+    // if ( distanceToTopEdge > 0 ) {
+    //   translationDelta.y = -distanceToTopEdge;
+    // }
     if ( distanceToRightEdge < 0 ) {
       translationDelta.x = -distanceToRightEdge;
     }
```
</details>

**Comment by jessegreenberg** [comment] 2023-10-04 17:58
Thanks @terracoda - I was wondering about overriding default behavior for sliders and *forcing* them to only respond to one set of keys. But we are going to bail on that part.

**Comment by jessegreenberg** [comment] 2023-10-04 19:20
OK, this change was pushed to main, and the option is used on the IntervalToolRectangle. @marlitas can you please review and make sure it is behaving as expected?

**Comment by marlitas** [comment] 2023-10-05 18:05
@jessegreenberg the commits look good and this is behaving the way I'd expect in the sim. Thanks again for your work on this! Over to @catherinecarter and @Nancy-Salpepi to review the final behavior on main.

**Comment by catherinecarter** [comment] 2023-10-05 19:48
The panning while zoomed looks great. The focus area stayed where I wanted it to when moving right/left with the interval tool.

**Comment by Nancy-Salpepi** [comment] 2023-10-05 23:45
Panning with alt input while zoomed in looks good now 🙂.

I am seeing an issue when using the mouse. When zoomed in to the play area, the screen won't pan when I move the interval tool using the mouse. However, if I am zoomed in to the accordion box, the screen will pan when I move the interval tool. 


https://github.com/phetsims/center-and-variability/assets/87318828/de033b0d-e50c-48c4-946d-d6cf8d066040

**Comment by jessegreenberg** [comment] 2023-10-06 15:07
This is actually the expected behavior after https://github.com/phetsims/scenery/issues/1381

>If [...] the globalBounds is larger than the screen size this function does nothing.
It doesn't make sense to try to keep the provided bounds entirely in view if they are larger than the availalable
view space.

Our new option might be able to improve this though, we could look into supporting only horizontal movement with mouse dragging in this case. Is that something we should do?

**Comment by Nancy-Salpepi** [comment] 2023-10-06 15:16
@jessegreenberg I thought about what you stated in https://github.com/phetsims/center-and-variability/issues/564#issuecomment-1750853503 when I posted my comment yesterday....
Which leads me to 2 questions
(1) is the interval tool actually 2 separate highlighted areas that just appear to move as one? 
(2) if the answer is yes, to the previous question, why doesn't the screen pan when I have the entire play area interval tool on the screen (see video below)? if the answer is no, then why does the screen pan when I move the interval tool in the accordion panel?

I hope this makes sense.

https://github.com/phetsims/center-and-variability/assets/87318828/b9c3298c-52d4-4e2c-b83c-b873e2d60fca

**Comment by marlitas** [comment] 2023-10-06 15:45
> why doesn't the screen pan when I have the entire play area interval tool on the screen (see video below)?

Technically the play area interval tool goes up and behind the accordion box so it would not be on the screen in the recording you showed.

**Comment by marlitas** [comment] 2023-10-06 15:47
According to @jessegreenberg's comment this seems like it is the desired behavior, but supporting horizontal movement with mouse dragging in this case would make sense to me as well. Does that feels like a relatively easy change @jessegreenberg?

**Comment by jessegreenberg** [comment] 2023-10-06 17:27
Yes I think so, it would be a change in the logic around here: 

https://github.com/phetsims/scenery/blob/8043c420e70be130e8cbf1238dfa028ca4713565/js/listeners/AnimatedPanZoomListener.ts#L919-L923

Like if the panDirection are provided to that function we would still try to pan in one dimension.

I am a bit behind on some other tasks today though, I might not be able to test until Monday.

**Comment by marlitas** [comment] 2023-10-06 17:28
@jessegreenberg that makes sense. I was just starting to dive into that. @jonathanolson and I may take a look in a bit, does that feel okay or would you rather us wait until you're available?

**Comment by jessegreenberg** [comment] 2023-10-06 17:29
Makes sense and please go ahead, no need to wait!

**Comment by marlitas** [comment] 2023-10-06 18:23
@jessegreenberg, @jonathanolson and I committed a fix for this. We added a new function `getTargetNodeDuringDrag` so that we could easily access the `panDirection` of the target node when calling `keepBoundsInView`

Over to you for code review, and over to @Nancy-Salpepi to check behavior on main.

**Comment by Nancy-Salpepi** [comment] 2023-10-06 18:52
Everything is working swimmingly!

**Comment by jessegreenberg** [comment] 2023-10-09 17:02
I reviewed the change and also tried it out in another sim, its working great. Thanks @marlitas and @jonathanolson!

`FocusPanDirection` now has behavior for more than focus, so I think I will rename this option and type.

**Comment by jessegreenberg** [comment] 2023-10-09 17:25
Alright, rename done. Back to @marlitas.

**Comment by marlitas** [comment] 2023-10-09 17:40
Thanks @jessegreenberg! I think this issue is ready to close.

**Closed by marlitas** 2023-10-09 17:40 UTC
Labels: type:bug, design:alt-input, dev:alt-input, status:ready-for-review
