### ISSUE TITLE
Card cueing hand reappears in Standard PhET-io wrapper after additional kicks

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#541] opened 2023-09-07 20:43 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.5.1

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, the behavior of the card cueing hand seems buggy. If I move a card in Studio and then launch the sim, the sim will launch without the card cueing hand. Then, if more balls are kicked, the cueing hand reappears. 

@catherinecarter thought this was a bug. From Slack:
Catherine Carter
  [4:24 PM](https://phetsims.slack.com/archives/D041TMHAXUN/p1694118283602379)
True. I still feel like it’s a bug since you have to take an action (kick 1) to make the cueing hand (re) appear. It would seem weird to have the sim launch without a hand but with cards already there, and then when kicking one more, a hand randomly appears. Even if a student isn’t going to kick another one, they could, and that seems like odd behavior. I’m going to call it a bug.

**Steps to reproduce**
1. In Studio, on the Median screen press kick 5 button
2. Move a card
3. Press kick 1 —> the cueing arrow doesn’t come back in Studio
4. Press the test button
5. In the standard phet-io wrapper --it opens without a cueing hand
6. Press kick 1 --cueing hand returns

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/1da6a401-70df-45e4-a030-a42b53a82122

**Comment by pixelzoom** [comment] 2023-09-13 17:12
This issue is related to this cueing hand:

<img width="212" alt="screenshot_2780" src="https://github.com/phetsims/center-and-variability/assets/3046552/961ced65-7d5a-460e-93c1-3910fb57e2a5">

... which is instantiated in InteractiveCardContainerNode:

```ts
    const handWithArrowNode = new Node( {
...
      visibleProperty: isDragIndicatorVisibleProperty
    } );
```

**Comment by pixelzoom** [comment] 2023-09-13 17:14
This issue is related to this cueing hand:

<img width="212" alt="screenshot_2780" src="https://github.com/phetsims/center-and-variability/assets/3046552/961ced65-7d5a-460e-93c1-3910fb57e2a5">

... which is instantiated in InteractiveCardContainerNode:

```ts
    const handWithArrowNode = new Node( {
...
      visibleProperty: isDragIndicatorVisibleProperty
    } );
```

... where `isDragIndicatorVisibleProperty` is:

```ts
    const isDragIndicatorVisibleProperty = new DerivedProperty( [ this.inputEnabledProperty, model.isKeyboardFocusedProperty ],
      ( inputEnabled, hasKeyboardFocus ) => inputEnabled && !hasKeyboardFocus );
```

... and `isKeyboardFocusedProperty` is not instrumented, and therefore not stateful:

```ts
  public readonly isKeyboardFocusedProperty = new BooleanProperty( false );
```

**Comment by pixelzoom** [comment] 2023-09-13 18:12
In the patch below, I instrumented InteractiveCardContainerNode `inputEnabledProperty` and InteractiveCardContainerModel `isKeyboardFocusedProperty`.  That did not fix the problem, and I doubted that it would -- I don't see how those dependencies could possibly set a correct value for `isDragIndicatorVisibleProperty`.

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] doc, https://github.com/phetsims/center-and-variability/issues/534
---
Index: js/median/model/InteractiveCardContainerModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/model/InteractiveCardContainerModel.ts b/js/median/model/InteractiveCardContainerModel.ts
--- a/js/median/model/InteractiveCardContainerModel.ts	(revision 5269bac7c2df8d3cd6426ba299fc1a639a49ccb6)
+++ b/js/median/model/InteractiveCardContainerModel.ts	(date 1694625763704)
@@ -78,15 +78,20 @@
   public readonly hasKeyboardSelectedDifferentCardProperty = new BooleanProperty( false );
 
   // Property that is triggered via focus and blur events in the InteractiveCardNodeContainer
-  public readonly isKeyboardFocusedProperty = new BooleanProperty( false );
+  public readonly isKeyboardFocusedProperty: Property<boolean>;
   public readonly manuallySortedEmitter: Emitter;
 
   public constructor( medianModel: MedianModel, providedOptions: InteractiveCardContainerModelOptions ) {
+
     super( medianModel, providedOptions );
 
     // Accumulated card drag distance, for purposes of hiding the drag indicator node
     this.totalDragDistanceProperty = new NumberProperty( 0 );
 
+    this.isKeyboardFocusedProperty = new BooleanProperty( false, {
+      tandem: providedOptions.tandem.createTandem( 'isKeyboardFocusedProperty' )
+    } );
+
     this.hasDraggedCardProperty = new DerivedProperty( [ this.totalDragDistanceProperty, this.hasKeyboardMovedCardProperty ], ( totalDragDistance, hasKeyboardMovedCard ) => {
       return totalDragDistance > 15 || hasKeyboardMovedCard;
     } );
Index: js/median/view/InteractiveCardNodeContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/median/view/InteractiveCardNodeContainer.ts b/js/median/view/InteractiveCardNodeContainer.ts
--- a/js/median/view/InteractiveCardNodeContainer.ts	(revision 5269bac7c2df8d3cd6426ba299fc1a639a49ccb6)
+++ b/js/median/view/InteractiveCardNodeContainer.ts	(date 1694625786172)
@@ -31,9 +31,15 @@
 import SoccerCommonConstants from '../../../../soccer-common/js/SoccerCommonConstants.js';
 import InteractiveCueArrowNode from '../../../../soccer-common/js/view/InteractiveCueArrowNode.js';
 import checkboxCheckedSoundPlayer from '../../../../tambo/js/shared-sound-players/checkboxCheckedSoundPlayer.js';
+import optionize, { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
+import StrictOmit from '../../../../phet-core/js/types/StrictOmit.js';
 
 const FOCUS_HIGHLIGHT_Y_MARGIN = CAVConstants.CARD_SPACING + 3;
 
+type SelfOptions = EmptySelfOptions;
+
+type InteractiveCardNodeContainerOptions = SelfOptions & StrictOmit<CardNodeContainerOptions, 'inputEnabledProperty'>;
+
 export default class InteractiveCardNodeContainer extends CardNodeContainer {
 
   // Whether the cards were already sorted when a particular action was taken
@@ -46,9 +52,14 @@
                       private readonly isSortingDataProperty: Property<boolean>,
                       sceneModel: CAVSoccerSceneModel,
                       medianVisibleProperty: Property<boolean>,
-                      providedOptions: CardNodeContainerOptions
+                      providedOptions: InteractiveCardNodeContainerOptions
   ) {
-    super( model, sceneModel, medianVisibleProperty, providedOptions );
+
+    const options = optionize<InteractiveCardNodeContainerOptions, SelfOptions, CardNodeContainerOptions>()( {
+      phetioInputEnabledPropertyInstrumented: true // see https://github.com/phetsims/center-and-variability/issues/541
+    }, providedOptions );
+
+    super( model, sceneModel, medianVisibleProperty, options );
 
     this.celebrationNode = new CelebrationNode( model, this.cardMap, this.sceneModel.resetEmitter );
     this.addChild( this.celebrationNode );
```

</details>

Then I discovered this in InteractiveCardNodeContainer:

```
    const fadeInAnimation = new Animation( {
      duration: 0.5,
      targets: [ {
        property: handWithArrowNode.opacityProperty,
        to: 1,
        easing: Easing.QUADRATIC_IN_OUT
      } ]
    } );

    // Fade out the hand with arrow node
    const fadeOutAnimation = new Animation( {
      duration: 0.1,
      targets: [ {
        property: handWithArrowNode.opacityProperty,
        to: 0,
        easing: Easing.QUADRATIC_IN_OUT
      } ]
    } );
```

So `isDragIndicatorVisibleProperty` is not the whole story.  It's `handWithArrowNode.opacityProperty` that's responsible for making it `effectively` visible or invisible.   And `opacityProperty` is not stateful.

**Comment by pixelzoom** [comment] 2023-09-13 18:51
In the above commits, I factored all of the pieces of the "cueing hand" into their own class, `CardDragCueNode`.   There are no functional pr behavior changes in these commits -- all of the related code is simply in `CardDragCueNode`.

**Comment by pixelzoom** [comment] 2023-09-13 18:55
We might be able to get away with `opacity` not being stateful.   The problem might be with InteractiveCardContainerModel `dragIndicationCardProperty`, which is not instrumented and is therefore not stateful:

```ts
public readonly dragIndicationCardProperty: Property<CardModel | null>;
```

And the listener for `dragIndicationCardProperty` is what drives the animation that sets opacity:

```
 model.dragIndicationCardProperty.lazyLink( ( newCard, oldCard ) => {
...
      if ( oldCard && !newCard ) {
        fadeInAnimation.stop();
        fadeOutAnimation.start();
      }

      else if ( newCard && !oldCard ) {
        fadeOutAnimation.stop();
        fadeInAnimation.start();
      }
} );
```

I could not easily try instrumenting `dragIndicationCardProperty` because there is no `CardModelIO` type.

@marlitas @matthew-blackman Let's hop on Zoom and discuss how to proceed.

**Comment by pixelzoom** [comment] 2023-09-14 19:26
Discussed with @marlitas and @matthew-blackman.  I'm going to reimplement this aspect.  I'll try to use the same "drag indicator" terminology that appear for the soccer balls hand, see Studio subtree below.  And should therefore rename CardDragCueNode to CardDragIndicatorNode.

<img width="366" alt="screenshot_2786" src="https://github.com/phetsims/center-and-variability/assets/3046552/c66f7437-5995-49b7-9941-354e3ef077b6">

**Comment by pixelzoom** [comment] 2023-09-18 21:22
I made one commit above where I renamed a `const`.  When I ran the sim, I saw that the card drag indicator waw visibile at startup, see screenshot below.  So I reverted that commit, and I'm still seeing this problem. I'm hestitant to proceed when it's broken before I start.  @marlitas @matthew-blackman any idea what changed?  

<img width="1187" alt="screenshot_2788" src="https://github.com/phetsims/center-and-variability/assets/3046552/078af162-90ea-4fed-baec-6e5db1c2bfcd">

**Comment by pixelzoom** [comment] 2023-09-18 21:42
In the above commits, I renamed CardDragCueNode to CardDragIndicatorNode, and I fixed its initial opacity (which was the cause of https://github.com/phetsims/center-and-variability/issues/541#issuecomment-1724472827).

**Comment by pixelzoom** [comment] 2023-09-18 21:52
InteractiveCardContainerModel `hasDraggedCardProperty` is also relevant.  But we can't simply include it in the derivation of `isDragIndicatorVisibleProperty` because of the opacity animation.

```ts
  // Indicates whether the user has ever dragged a card. It's used to hide the drag indicator arrow after
  // the user dragged a card
  public readonly hasDraggedCardProperty: TReadOnlyProperty<boolean>;
```

**Comment by pixelzoom** [comment] 2023-09-18 21:57
@catherinecarter You requested the fade in/out animation in https://github.com/phetsims/center-and-variability/issues/273#issuecomment-1607717045.   It's resulting in a lot of complexity, and PhET-iO state problems.  It's also inconsistently applied to "drag indicators" -- in the screenshot below, the hand in the Distance accordion box fades in/out, while the hand in the soccer field just appear/disappears.  So I'd like to eliminate the fade in/out animation.  Is that OK?  Does anyone else object?

<img width="1187" alt="screenshot_2791" src="https://github.com/phetsims/center-and-variability/assets/3046552/00a5ef3e-1214-4b0a-ab79-06d67b9c2140">

**Comment by catherinecarter** [comment] 2023-09-18 22:00
@pixelzoom, I do not object to taking the animation out. 

When the hand appeared while soccer balls were still being kicked, the non-fade-just-appear seemed a little stark or harsh. So the fade seemed to soften the harshness of the hand appearing. But if it's creating issues with performance and PhET-iO related things, the removal of harshness is not worth it.

So yes, remove it if it makes things easier.

**Comment by pixelzoom** [comment] 2023-09-18 22:33
Summary of the above commits:

* Removed the fade in/out animation, so that the visibility of CardDragIndicatorNode is solely determined by its visibleProperty.
* Revised the derivation of CardDragIndicatorNode visibleProperty to include whether the model has identified a card that should display the drag indicator (`model.dragIndicationCardProperty`).
* Instrumented Properties that are required for the derivation of `dragIndicationCardProperty`. Those Properties are `totalDragDistanceProperty` and `hasKeyboardMovedCardProperty`, which are used to derive `hasDraggedCardProperty`, which in turn sets `dragIndicationCardProperty`. These Propertied must be stateful if `dragIndicationCardProperty` is to have the proper value in the Standard wrapper.  This required a PhET-iO API change.

@Nancy-Salpepi please verify that the behavior is correct. 

@marlitas @matthew-blackman Please review the changes, let me know if you have any questions. Also please double-check the behavior. 

@catherinecarter please have a look to make sure that you're OK with not having the fade in/out animation. 

If everything is OK, the last one assigned can close this issue.

**Comment by marlitas** [comment] 2023-09-18 23:45
@pixelzoom, these changes look good and the instrumentation seems reasonable. It does feel like it cleaned some stuff up in the code which is nice.

A couple of grammar fixes in nearby documentation above, but otherwise is good to go. Tested in studio, phet-io brand, and state wrapper. All seem to be working appropriately.

Thanks for the work here @pixelzoom. @catherinecarter / @Nancy-Salpepi  this is ready to close once you approve changes look good.

**Comment by Nancy-Salpepi** [comment] 2023-09-18 23:49
The current behavior in studio on main looks correct. If I move a card in studio, the hand cue is not present in the Standard PhET-iO wrapper when launched, nor does is reappear after more balls are kicked.

**Comment by catherinecarter** [comment] 2023-09-19 14:23
I still like the fade a little better :) but not enough to force the issue. Especially if it means the behavior in all cases works much better without it. 

Closing, and thanks for working so hard on this!

**Closed by catherinecarter** 2023-09-19 14:23 UTC
Labels: type:bug, status:ready-for-review
