### ISSUE TITLE
Focus highlight on Kick 1 button disappears with one kick left

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#77] opened 2022-03-07 18:03 UTC
**Test device**
Macbook Air (m1 chip)

**Operating System**
12.2.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/781:
The focus highlight around the Kick 1 button disappears when there is only one kick left. Pressing space doesn't kick the last ball. I need to press tab again to return focus to that button.
**Steps to reproduce**
1. On screen 1 or 2: Press tab to highlight the Kick 1 button. 
2. Press spacebar until 14 balls are in the play area--the Kick 1 button is no longer the focus.

This also occurs when a combo of kick buttons is used to reach 14 or when mouse followed by keyboard nav is used. 

**Visuals**

https://user-images.githubusercontent.com/87318828/157091292-c633a6c0-71e6-48f7-96c3-13899a8eef10.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
Language: en-US
Window: 980x467
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment] 2022-03-08 01:17
I also see this when the 'return' key is used instead of the spacebar.

**Comment by amanda-phet** [comment] 2022-03-11 18:43
This is a 1.0 priority, but would be good to consider sooner if possible.

**Comment by samreid** [comment] 2023-04-21 21:44
This is still happening and very easy to reproduce the problem, I will work on it.

**Comment by samreid** [comment] 2023-04-21 22:03
I'll need help on this one. The problem is that `numberOfRemainingKickableSoccerBallsProperty` temporarily goes to 0 so the button is made invisible, then visible quickly. So it loses focus.  Here's my investigative patch so far:

<details>

```diff

Subject: [PATCH] Convert -1 to null, see https://github.com/phetsims/center-and-variability/issues/59
---
Index: main/scenery/js/accessibility/pdom/ParallelDOM.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/scenery/js/accessibility/pdom/ParallelDOM.ts b/main/scenery/js/accessibility/pdom/ParallelDOM.ts
--- a/main/scenery/js/accessibility/pdom/ParallelDOM.ts	(revision bc5f70afab1993ded43cf4bc694b743f065a1278)
+++ b/main/scenery/js/accessibility/pdom/ParallelDOM.ts	(date 1682113885447)
@@ -704,6 +704,14 @@
     }
   }
 
+  public addEventListener( type: string, listener: ( event: Event ) => void ): void {
+    if ( this._pdomInstances.length > 0 ) {
+      const peer = this._pdomInstances[ 0 ].peer!;
+      assert && assert( peer, 'must have a peer to addEventListener' );
+      peer.blur();
+    }
+  }
+
   /**
    * Called when assertions are enabled and once the Node has been completely constructed. This is the time to
    * make sure that options are set up the way they are expected to be. For example. you don't want accessibleName
Index: main/center-and-variability/js/common/view/KickButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/center-and-variability/js/common/view/KickButtonGroup.ts b/main/center-and-variability/js/common/view/KickButtonGroup.ts
--- a/main/center-and-variability/js/common/view/KickButtonGroup.ts	(revision a7ae0de56d9b3a1d826af62f46a16974f341d424)
+++ b/main/center-and-variability/js/common/view/KickButtonGroup.ts	(date 1682114263391)
@@ -61,7 +61,7 @@
         tandem: tandem.createTandem( 'visibleProperty' )
       } );
 
-      return new RectangularPushButton( {
+      const rectangularPushButton = new RectangularPushButton( {
         visibleProperty: DerivedProperty.and( [ model.hasKickableSoccerBallsProperty, buttonVisibleProperty ] ),
         content: content.label,
         baseColor: CAVColors.kickButtonFillColorProperty,
@@ -78,6 +78,27 @@
         // https://github.com/phetsims/center-and-variability/issues/102
         fireOnHoldInterval: 650
       } );
+
+      rectangularPushButton.visibleProperty.link( visible => {
+        if ( !visible ) {
+          debugger;
+        }
+      } );
+      // get the primary peer
+      setTimeout( () => {
+        const peer = rectangularPushButton._pdomInstances[ 0 ].peer!;
+        // debugger;
+        peer._primarySibling.addEventListener( 'blur', () => {
+          // debugger;
+        } );
+      }, 1000 );
+
+      // add event listener for blur
+      // peer.addEventListener( 'blur', () => {
+      //   debugger;
+      // } );
+
+      return rectangularPushButton;
     };
 
     // Create tandems so the labels can appear at the proper place in the tandem tree
Index: main/center-and-variability/js/common/model/SoccerModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/center-and-variability/js/common/model/SoccerModel.ts b/main/center-and-variability/js/common/model/SoccerModel.ts
--- a/main/center-and-variability/js/common/model/SoccerModel.ts	(revision a7ae0de56d9b3a1d826af62f46a16974f341d424)
+++ b/main/center-and-variability/js/common/model/SoccerModel.ts	(date 1682114502945)
@@ -35,7 +35,7 @@
 type SoccerModelOptions = SelfOptions & CAVModelOptions;
 
 // constants
-const TIME_BETWEEN_RAPID_KICKS = 0.5; // in seconds
+const TIME_BETWEEN_RAPID_KICKS = 0.01; // in seconds
 
 class SoccerModel extends CAVModel {
   public readonly soccerPlayerGroup: PhetioGroup<SoccerPlayer, [ number ]>;
@@ -88,12 +88,16 @@
                                        nextBallToKick ) => {
 
       const numberOfCreatedButKickableBalls = nextBallToKick === null ? 0 : 1;
-      return numberOfRemainingObjects - numberOfScheduledBallsToKick + numberOfCreatedButKickableBalls;
+      const newVar = numberOfRemainingObjects - numberOfScheduledBallsToKick + numberOfCreatedButKickableBalls;
+      console.log( `numberOfRemainingObjects: ${numberOfRemainingObjects}, numberOfScheduledBallsToKick: ${numberOfScheduledBallsToKick}, nextBallToKick: ${nextBallToKick}, newVar: ${newVar}` );
+      return newVar;
     } );
 
     this.hasKickableSoccerBallsProperty = new DerivedProperty( [ this.numberOfRemainingKickableSoccerBallsProperty ],
       numberOfRemainingKickableObjects => numberOfRemainingKickableObjects > 0 );
 
+    this.hasKickableSoccerBallsProperty.debug( 'hasKickableSoccerBallsProperty' );
+
     this.distributionProperty = new Property( SoccerModel.chooseDistribution(), {
       tandem: options.tandem.createTandem( 'distributionProperty' ),
       phetioValueType: ArrayIO( NumberIO ),

```

</details>

**Comment by samreid** [comment] 2023-05-12 04:55
This is still buggy. Here is an updated patch:

<details>

```diff

Subject: [PATCH] Uninstrument play area drag indicator visible property, see https://github.com/phetsims/center-and-variability/issues/129
---
Index: main/scenery/js/accessibility/pdom/ParallelDOM.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/scenery/js/accessibility/pdom/ParallelDOM.ts b/main/scenery/js/accessibility/pdom/ParallelDOM.ts
--- a/main/scenery/js/accessibility/pdom/ParallelDOM.ts	(revision bb2ea3a8c08144267b1ec8c4755c1e96d3825080)
+++ b/main/scenery/js/accessibility/pdom/ParallelDOM.ts	(date 1683866944696)
@@ -704,6 +704,14 @@
     }
   }
 
+  public addEventListener( type: string, listener: ( event: Event ) => void ): void {
+    if ( this._pdomInstances.length > 0 ) {
+      const peer = this._pdomInstances[ 0 ].peer!;
+      assert && assert( peer, 'must have a peer to addEventListener' );
+      peer.blur();
+    }
+  }
+
   /**
    * Called when assertions are enabled and once the Node has been completely constructed. This is the time to
    * make sure that options are set up the way they are expected to be. For example. you don't want accessibleName
Index: main/center-and-variability/js/common/view/KickButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/center-and-variability/js/common/view/KickButtonGroup.ts b/main/center-and-variability/js/common/view/KickButtonGroup.ts
--- a/main/center-and-variability/js/common/view/KickButtonGroup.ts	(revision 2424a5d58298fe586d61ff7a243fda45d34cc370)
+++ b/main/center-and-variability/js/common/view/KickButtonGroup.ts	(date 1683866944686)
@@ -67,7 +67,7 @@
       //     return model.selectedSceneModelProperty.value.hasKickableSoccerBallsProperty.value;
       //   } );
 
-      return new RectangularPushButton( {
+      const rectangularPushButton = new RectangularPushButton( {
         visibleProperty: DerivedProperty.and( [ hasKickableSoccerBallsProperty, isButtonVisibleProperty ] ),
         content: content.label,
         baseColor: CAVColors.kickButtonFillColorProperty,
@@ -84,6 +84,27 @@
         // https://github.com/phetsims/center-and-variability/issues/102
         fireOnHoldInterval: 650
       } );
+
+      rectangularPushButton.visibleProperty.link( visible => {
+        if ( !visible ) {
+          debugger;
+        }
+      } );
+      // get the primary peer
+      setTimeout( () => {
+        const peer = rectangularPushButton._pdomInstances[ 0 ].peer!;
+        // debugger;
+        peer._primarySibling.addEventListener( 'blur', () => {
+          // debugger;
+        } );
+      }, 1000 );
+
+      // add event listener for blur
+      // peer.addEventListener( 'blur', () => {
+      //   debugger;
+      // } );
+
+      return rectangularPushButton;
     };
 
     // Create tandems so the labels can appear at the proper place in the tandem tree
Index: main/center-and-variability/js/common/model/CAVSceneModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/center-and-variability/js/common/model/CAVSceneModel.ts b/main/center-and-variability/js/common/model/CAVSceneModel.ts
--- a/main/center-and-variability/js/common/model/CAVSceneModel.ts	(revision 2424a5d58298fe586d61ff7a243fda45d34cc370)
+++ b/main/center-and-variability/js/common/model/CAVSceneModel.ts	(date 1683867174529)
@@ -245,6 +245,7 @@
       this.maxKicksProperty,
       this.numberOfScheduledSoccerBallsToKickProperty,
       ...this.soccerBalls.map( soccerBall => soccerBall.valueProperty ),
+      ...this.soccerBalls.map( soccerBall => soccerBall.isActiveProperty ),
       ...this.soccerBalls.map( soccerBall => soccerBall.animationModeProperty ) ], () => {
 
       const kickedSoccerBalls = this.getActiveSoccerBalls().filter(
@@ -254,12 +255,15 @@
       );
       const value = this.maxKicksProperty.value - kickedSoccerBalls.length - this.numberOfScheduledSoccerBallsToKickProperty.value;
 
+      console.log( 'numberOfUnkickedBallsProperty', value );
       return value;
     } );
 
     this.hasKickableSoccerBallsProperty = new DerivedProperty( [ this.numberOfUnkickedBallsProperty ],
       numberOfUnkickedBalls => numberOfUnkickedBalls > 0 );
 
+    this.hasKickableSoccerBallsProperty.debug( 'hasKickableSoccerBallsProperty' );
+
     this.distributionProperty = new Property( initialDistribution, {
       tandem: options.tandem.createTandem( 'distributionProperty' ),
       phetioValueType: ArrayIO( NumberIO ),

```

</details>

Perhaps when kicking, we need to create the new ball right before kicking the previous ball, so it will know we aren't down to 0?

**Comment by samreid** [comment] 2023-06-09 04:03
This works correctly, but I think we can do better by updating something in `step`:

<details>

```diff

Subject: [PATCH] Remove unused number tones, see https://github.com/phetsims/center-and-variability/issues/217
---
Index: js/common/view/KickButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/KickButtonGroup.ts b/js/common/view/KickButtonGroup.ts
--- a/js/common/view/KickButtonGroup.ts	(revision c4c7151dcb0f037ba513ca71df2e42c5c67416d2)
+++ b/js/common/view/KickButtonGroup.ts	(date 1686283372884)
@@ -23,6 +23,7 @@
 import CAVModel from '../model/CAVModel.js';
 import DynamicProperty from '../../../../axon/js/DynamicProperty.js';
 import CAVSceneModel from '../model/CAVSceneModel.js';
+import animationFrameTimer from '../../../../axon/js/animationFrameTimer.js';
 
 type SelfOptions = EmptySelfOptions;
 export type KickButtonGroupOptions = SelfOptions & VBoxOptions & PickRequired<VBoxOptions, 'tandem'>;
@@ -54,18 +55,26 @@
         tandem: tandem.createTandem( 'visibleProperty' )
       } );
 
-
       const hasKickableSoccerBallsProperty = new DynamicProperty<boolean, unknown, CAVSceneModel>( model.selectedSceneModelProperty, {
         derive: 'hasKickableSoccerBallsProperty'
       } );
 
-      // const hasKickableSoccerBallsProperty =
-      //   DerivedProperty.deriveAny( [ model.selectedSceneModelProperty, ...model.sceneModels.map( scene => scene.hasKickableSoccerBallsProperty ) ], () => {
-      //     return model.selectedSceneModelProperty.value.hasKickableSoccerBallsProperty.value;
-      //   } );
+      //
+      const buttonVisibleProperty = DerivedProperty.and( [ hasKickableSoccerBallsProperty, isButtonVisibleProperty ] );
+      const batchedButtonVisibleProperty = new BooleanProperty( buttonVisibleProperty.value );
+
+      let batchedValue = buttonVisibleProperty.value;
+      buttonVisibleProperty.link( visible => {
+
+        // last one wins
+        batchedValue = visible;
+        animationFrameTimer.runOnNextTick( () => {
+          batchedButtonVisibleProperty.value = batchedValue;
+        } );
+      } );
 
       return new RectangularPushButton( {
-        visibleProperty: DerivedProperty.and( [ hasKickableSoccerBallsProperty, isButtonVisibleProperty ] ),
+        visibleProperty: batchedButtonVisibleProperty,
         content: content,
         baseColor: CAVColors.kickButtonFillColorProperty,
         xMargin: 12,

```

</details>

**Comment by samreid** [comment] 2023-06-09 04:09
Fixed in the commit.  @marlitas or @matthew-blackman would you please review? Close if all is well.

**Comment by marlitas** [comment] 2023-06-16 16:14
@samreid, @matthew-blackman and I reviewed together and we agree this is a working approach, and do not know what other options we have. Closing.

**Closed** 2023-06-16 16:14 UTC
Labels: type:bug, dev:alt-input, status:ready-for-review
