### ISSUE TITLE
Keyboard support for moving soccer balls

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#162] opened 2023-04-27 14:23 UTC
@amanda-phet noticed when tabbing that the cards on the Median screen and the soccer balls are skipped. I met with @terracoda  to discuss options for how to best handle the functionality, and here are some options: 
1. Option 1: On the median screen, pressing Tab will move from card to card (in accordion box) or stack to stack (in the ball area). On the cards, the arrows or A/D will move the cards left and right. Same with the balls, but only the ball at the top of the stack will move with arrows/A/D. (Same idea for the Mean & Median and Variability screens, except no tabbing is needed in the accordion box with the dot/line plot). 
2.  Option 2: Custom functionality where the entire block of balls are highlighted, then a key command such as: J + (tick mark number) would jump to the position on the number line. Then, space would grab the top ball of the stack, and another J + (tick mark number) would place the ball to its new position. This functionality is less intuitive for the cards on the Median screen. 

Taliesin said there could be more options since the interactions can be customized, but this is a good starting place to think about how we want the tabbing to function.

**Comment by terracoda** [comment] 2023-04-28 00:01
I also would like to make it clear that this interaction is a completely novel one - lots of dragging and dropping, with a connected representation that is also interactive.

I would recommend some sim team brainstorming and maybe the implementation of a couple of options. Then some verification with keyboard users.

**Comment by terracoda** [comment] 2023-04-28 00:07
And to add to Option 1 described by Cathy, on the field, the Tab key would need to take the learner's focus to the next stack of balls, then once on a ball the ball could be repositioned left or right.

I have a feeling both options could require some kind of two-step grabbing when on a ball.

The cards in the median accordion box seem more like a typical sort-type of interaction. There should be existing interaction patterns for that, though we haven't done one for PhET.

**Comment by terracoda** [comment] 2023-04-28 00:40
I am not sure option 2 is un-intuitive, but I think it needs a full discussion, and a full understanding of the relationship between the kicked balls and the data cards.

It is great that you are thinking about the interaction from a different perspective.

**Comment by amanda-phet** [comment] 2023-04-28 17:10
I think option 1 is the most logical. 

@terracoda Can you share your list of keyboard users recruited for interviews so @catherinecarter can solicit them when it's time to do interviews on this sim?

**Comment by matthew-blackman** [comment] 2023-05-08 16:25
@catherinecarter confirmed that she's okay with tabbing to each stack and using the arrow keys to move the top ball in that stack if highlighted (without needing to hit spacebar). 

Question for @terracoda: What would be the expected UX for the spacebar and arrow keys here? Would the user expect to need to hit the space bar to "pick up" a ball in the highlighted stack, or just go straight to the arrow keys once a stack is highlighted?

**Comment by terracoda** [comment] 2023-05-08 17:20
Hey folks, just an FYI, most of the keyboard users I have on my list either have low vision or no vision. I do not have a list of keyboard users with vision.

Re the expected UX for space bar: 
People who can see & who use the keyboard will not know they need to hit space if the interaction does not look like a button. In PhET's grab & drag/move interactions, visual users needed a visual hint to "Press Space to Grab or Release". If you want to use PhET's 2-step grab interaction, you will need to provide a visual hint.
<img width="279" alt="Screen Shot 2023-05-08 at 2 20 09 PM" src="https://user-images.githubusercontent.com/1902116/236883061-c1573664-5542-4f62-b67b-7e78872c697c.png">

That said, you may not need a a 2-step grab interaction. This interaction is **different** than the typical single-object grab and drag.

What I think is interesting and important about this interaction is the grouping, though I am not 100 percent sure.

Regardless, no matter how you slice it, the interaction will be a custom interaction and will likely need to be explained to learners through the keyboard shortcuts dialog (and potentially in an initial visual hint). There is no built-in native HTML interaction for a field of grabb-able and movable soccer balls. But learners do try things. Learners with vision will likely try the arrow keys. They might try the space key and arrow keys.

There are potentially some UX patterns that are similar to this interaction, like how you re-order things in a list or in a menu. We could look into the established keyboard patterns for re-ordering menus/lists to see if there is a good fit.

**What I think needs to happen here** is some brainstorming on what is desired and what is possible to create an efficient and intuitive (i.e., memorable after getting one on-screen hint or memorable after reading instructions once) grab and drag for the cards and soccer balls.

The problem with creating Tab stops for every card and every stack of balls, is that a learner would have to traverse those tabs all the time no matter what they are trying to do. This would make keyboard navigation inefficient for learners who rely on the keyboard.

Is it possible to have a brainstorming meeting. What brain storming have you already done?

Also, FYI, going straight to the arrow keys (i.e., with out first pressing Space to grab) is something we have done in 2 sims (the ruler in Coulomb's Law and the Both Hands interaction in Ratio and Proportion). I think if we were to re-release CL, it would get a grab & drag ruler like in Gravity Force Lab. In RaP, the interaction is bi-manual, so it is a bit different and the individual sliders scaffold the use of arrow keys, so we decided to not use the 2-step grab & drag there.

I suggest a meeting.

**Comment by terracoda** [comment] 2023-05-12 16:15
Definitely, a good stepping stone. It will give you a feel for the number of tap stops.

**Comment by samreid** [comment] 2023-05-16 00:44
I got basic keyboard support working on the soccer balls in this patch:

<details>

```diff

Subject: [PATCH] Allow dragging the interval tool rectangle to translate it, see https://github.com/phetsims/center-and-variability/issues/194
---
Index: js/common/view/SoccerBallNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/SoccerBallNode.ts b/js/common/view/SoccerBallNode.ts
--- a/js/common/view/SoccerBallNode.ts	(revision ae7b8d12d681776deb8989ae660051bcbafa109b)
+++ b/js/common/view/SoccerBallNode.ts	(date 1684197480021)
@@ -25,7 +25,9 @@
     // Use the y dimension, since it determines how the soccer balls stack. But maintain the same aspect ratio as the image
     const viewRadius = Math.abs( modelViewTransform.modelToViewDeltaY( CAVObjectType.SOCCER_BALL.radius ) );
 
-    super( soccerBall, isPlayAreaMedianVisibleProperty, modelViewTransform, CAVObjectType.SOCCER_BALL.radius, options );
+    super( soccerBall, isPlayAreaMedianVisibleProperty, modelViewTransform, CAVObjectType.SOCCER_BALL.radius, {
+      ...options
+    } );
 
     // The dark soccer ball is used for when a ball has input disabled.
     const soccerBallNode = new Image( ball_png );
Index: js/common/view/DataPointNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/DataPointNode.ts b/js/common/view/DataPointNode.ts
--- a/js/common/view/DataPointNode.ts	(revision ae7b8d12d681776deb8989ae660051bcbafa109b)
+++ b/js/common/view/DataPointNode.ts	(date 1684197794417)
@@ -67,6 +67,9 @@
           this.moveToFront();
         }
       } );
+
+    // TODO: https://github.com/phetsims/center-and-variability/issues/162 this doesn't seem to disable focus
+    this.myEnabledProperty.value = false;
   }
 }
 
Index: js/common/view/CAVObjectNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CAVObjectNode.ts b/js/common/view/CAVObjectNode.ts
--- a/js/common/view/CAVObjectNode.ts	(revision ae7b8d12d681776deb8989ae660051bcbafa109b)
+++ b/js/common/view/CAVObjectNode.ts	(date 1684197758171)
@@ -19,6 +19,10 @@
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
 import Multilink from '../../../../axon/js/Multilink.js';
+import AccessibleSlider from '../../../../sun/js/accessibility/AccessibleSlider.js';
+import Property from '../../../../axon/js/Property.js';
+import Range from '../../../../dot/js/Range.js';
+import CAVConstants from '../CAVConstants.js';
 
 export type CAVObjectNodeOptions =
 
@@ -26,9 +30,10 @@
   & StrictOmit<NodeOptions, 'inputEnabledProperty'>
   & PickRequired<NodeOptions, 'tandem'>;
 
-export default abstract class CAVObjectNode extends Node {
+export default abstract class CAVObjectNode extends AccessibleSlider( Node, 0 ) {
 
   protected readonly medianHighlight: Circle;
+  protected readonly myEnabledProperty: Property<boolean>;
 
   public constructor( public readonly soccerBall: SoccerBall,
                       isPlayAreaMedianVisibleProperty: TReadOnlyProperty<boolean>,
@@ -36,13 +41,23 @@
                       modelRadius: number,
                       providedOptions?: CAVObjectNodeOptions ) {
 
-    const options = optionize<CAVObjectNodeOptions, EmptySelfOptions, NodeOptions>()( {
-      cursor: 'pointer'
-    }, providedOptions );
-    super( options );
+    const enabledProperty = new Property( true );
+
+    super( {
+      enabledRangeProperty: new Property( CAVConstants.PHYSICAL_RANGE ),
+      valueProperty: soccerBall.valueProperty,
+      cursor: 'pointer',
+      keyboardStep: 1,
+      shiftKeyboardStep: 1,
+      pageKeyboardStep: 5,
+      ...providedOptions,
+      enabledProperty: enabledProperty
+    } );
 
     const viewRadius = modelViewTransform.modelToViewDeltaX( modelRadius );
 
+    this.myEnabledProperty = enabledProperty;
+
     // Visibilty controlled by subclass logic. Also this whole node is moved to front when the medianHighlight is shown
     // so it will appear in front (unless the user drags another object on top of it).
     this.medianHighlight = new Circle( viewRadius + 1.75, {

```

</details>

But we will probably need to:
* separate the inheritance hierarchy since data points and soccer balls share an ancestor, and we would like to extend AccessibleValueHandler only for the soccer balls.
* find a way to only focus the soccers balls at the top of the stack.  enabledProperty didn't seem to work

**Comment by samreid** [comment] 2023-05-17 03:58
I committed an initial draft, with some TODOs in the code.

**Comment by samreid** [comment] 2023-05-20 21:35
There was a problem during reset/clear, so I went ahead and switched to DynamicProperty.

**Comment by jessegreenberg** [comment] 2023-06-09 19:45
@samreid @marlitas and I met today to look into a bug where the soccer ball gets stuck when using keyboard input. It only seems to happen when the ball moves onto a tall stack. We tried removing some of the `moveToFront` calls in case they were causing this but that had no impact. In the a11y view we noticed a weird behavior where the soccer ball lost focus, but the focus highlight remained in the sim. I think this is related, Ill continue to investigate.

**Comment by jessegreenberg** [comment] 2023-06-09 21:16
OK, the above commit fixes the problem and I believe makes sense for the implementation. But I would like to understand why the original code had this bug.

**Comment by jessegreenberg** [comment] 2023-06-09 21:57
I found this was caused by https://github.com/phetsims/scenery/commit/e56769f94cf85c9b3e055aba2abeed7a9e526bf6 for https://github.com/phetsims/scenery/issues/1550. Particularly
https://github.com/phetsims/scenery/blob/9715e028ad530f753d4849a9145fe46f7271bdf2/js/accessibility/pdom/PDOMTree.js#L396-L399

The `document.activeElement.id` is from the Node's PartialPDOMTrail **before** the reorder operation. After the PDOM reorder, the trail changes and it is impossible to restore focus to the element in the `afterOp`. The result in this case is the ball getting stuck because nothing has focus. To be continued in scenery.

**Comment by samreid** [comment] 2023-06-13 04:01
I feel @jessegreenberg fixed a sim-specific problem when he moved the soccer ball PDOM ordering to the correct layer in https://github.com/phetsims/center-and-variability/commit/a22659bfe6fd9ea9619f34f6e4ef1787bef5a590, and he indicated the common code work will continue in https://github.com/phetsims/scenery/issues/1550.  The behavior works much better in the sim, so I feel this sim-specific issue can be closed.

**Comment by phet-dev** [comment] 2023-06-13 09:40
Reopening because there is a TODO marked for this issue.

**Closed** 2023-06-13 14:07 UTC
Labels: dev:help-wanted
