### ISSUE TITLE
intervalTool.isInputEnabledProperty changes back to true after moving handle

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#538] opened 2023-09-06 19:06 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/976, after disabling centerAndVariability.variabilityScreen.model.soccerArea.intervalTool.isInputEnabledProperty, moving a handle cause the property to become enabled again. 

**Steps to reproduce**
1. Go to centerAndVariability.variabilityScreen.model.soccerArea.intervalTool.isInputEnabledProperty and uncheck box to change the property to false.
2. Move a handle --property becomes true again
--This also happens if you launch the sim after step 1 and then move a handle.

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/8bec8ed3-950e-45e5-b763-dfef3d7851b6

**Comment by pixelzoom** [comment] 2023-09-12 20:09
Reproduced in main.  Also noting that when one of the handles is dragged, `isIntervalToolInputEnabledProperty` becomes true on drag start, and false on drag end.  So apparently it always reverts to true on drag end.

According to the phetioDocumentation in VariabilityModel.ts, the intervalTool is working as expected - this Property only affects translation. (Side note: Based on this doc, and the actual behavior, the name `isIntervalToolInputEnabledProperty` is confusing. Consider renaming it to something like `isIntervalToolTranslationEnabledProperty`.)

```ts
    this.isIntervalToolInputEnabledProperty = new BooleanProperty( true, {
      tandem: intervalToolTandem.createTandem( 'isInputEnabledProperty' ),
      phetioFeatured: true,
      phetioDocumentation: 'When false, the interval cannot be translated left/right, but the handles are still moveable/interactive.'
    } );
```

I don't see anything explictly doing `isIntervalToolInputEnabledProperty.value =`  or `isIntervalToolInputEnabledProperty.setValue`, so it's unclear why the value is changing.

**Comment by pixelzoom** [comment] 2023-09-12 20:11
Is it possible that `isIntervalToolInputEnabledProperty` is controlled by the sim, and should therefore be `phetioReadOnly: true`?

**Comment by pixelzoom** [comment] 2023-09-12 20:15
The handles are instances of IntervalToolPredictionSlider, instantiated in VariabilityScreenView:

```ts
    const handle1 = new IntervalToolPredictionSlider( model.intervalTool1ValueProperty, this.modelViewTransform, CAVConstants.VARIABILITY_DRAG_RANGE,
      isIntervalHandle1BeingDraggedProperty, new BooleanProperty( false ), combineOptions<PredictionSliderOptions>( {
        valueProperty: model.intervalTool1ValueProperty,
        tandem: toolHandle1Tandem
      }, createPredictionSliderOptions( toolHandle1Tandem ) ) );

    const handle2 = new IntervalToolPredictionSlider( model.intervalTool2ValueProperty, this.modelViewTransform, CAVConstants.VARIABILITY_DRAG_RANGE,
      isIntervalHandle2BeingDraggedProperty, new BooleanProperty( false ), combineOptions<PredictionSliderOptions>( {
        valueProperty: model.intervalTool2ValueProperty,
        tandem: toolHandle2Tandem
      }, createPredictionSliderOptions( toolHandle2Tandem ) ) );
```

**Comment by pixelzoom** [comment] 2023-09-12 20:20
I'm betting it's related to this DragListener, in PredictionSlider (the superclass of IntervalToolPredictionSlider).  The boolean values set on `start` and `end` here are the inverse of the change observed in `isIntervalToolInputEnabledProperty`.

```ts
    this.addInputListener( new DragListener( {
      tandem: options.tandem.createTandem( 'dragListener' ),
      positionProperty: this.dragPositionProperty,
      start: () => {
        if ( options.isMouseTouchDraggingProperty ) {
          options.isMouseTouchDraggingProperty.value = true;
        }
        this.moveToFront();
      },
      end: () => {
        if ( options.isMouseTouchDraggingProperty ) {
          options.isMouseTouchDraggingProperty.value = false;
        }
      }
    } ) );
```

**Comment by pixelzoom** [comment] 2023-09-12 20:25
In VariabilityScreenView, `isIntervalAreaBeingDraggedProperty` is being used as the `inputEnabledProperty` for IntervalToolNode:

```ts
    const intervalToolNode = new IntervalToolNode( model.intervalTool1ValueProperty, model.intervalTool2ValueProperty, this.modelViewTransform,
      new DerivedProperty( [ variabilityAccordionBox.boundsProperty ], bounds => bounds.top ), isIntervalAreaBeingDraggedProperty, {
        visibleProperty: model.isIntervalToolVisibleProperty,
        inputEnabledProperty: model.isIntervalToolInputEnabledProperty,
        phetioEnabledPropertyInstrumented: false,
        tandem: intervalToolNodeTandem
      } );
```

Also in VariableScreenView.ts, `isIntervalToolInputEnabledProperty` is then being set indirectly by setting `intervalToolNode.inputEnabled`:

```ts
    // Prevent multitouch on the intervalToolNode if the user is manipulating either of the arrow handles, see https://github.com/phetsims/center-and-variability/issues/225
    Multilink.multilink( [ handle1.isKeyboardDraggingProperty, handle1.isMouseTouchDraggingProperty, handle2.isKeyboardDraggingProperty, handle2.isMouseTouchDraggingProperty ], ( keyboard1, mouse1, keyboard2, mouse2 ) => {
      intervalToolNode.inputEnabled = !keyboard1 && !mouse1 && !keyboard2 && !mouse2;
    } );
```

So `isIntervalToolInputEnabledProperty` is under control of the sim, in a very confusing roundabout way.  Unless you're prepared to do some reimplementation, it should be `phetioReadOnly: true`.

**Comment by marlitas** [comment] 2023-09-12 20:52
Hmmm... this is unfortunate because having the translation enabling being instrumented and being able to separately instrument the enabledProperties of both handles was a specific PhET-iO request by the design and KP. 

We may need to re-implement. 

I went ahead with the rename. I think that's a great idea and much clearer on the Property's exact purpose. Thanks for the investigation @pixelzoom.

**Comment by marlitas** [comment] 2023-09-12 21:15
Talked this through with @pixelzoom.

There's a lot of gymnastics going on in the intervalTool. We think it might be best to move the handles to live under the IntervalToolNode. This is causing us to have to create a gatedVisible property for each handle, create tandem gymnastics, and confuses the enabledProperty.

We should restructure this implementation so that the handles and the rectangle all live together.

**Comment by pixelzoom** [comment] 2023-09-12 22:15
Some more thoughts...  Rework IntervalToolNode so that it is the parent for all parts of the interval tool, and the class and Studio tree both have the PhET-iO elements and Studio tree structure shown below.  `selfVisibleProperty` will become unnecessary for the handles, because "Interval Tool" checkbox be controlling `intervalTooNode.visibleProperty`, and not the `visibleProperty` of the handles.

```
-intervalTooNode
  *visibleProperty => model.soccerArea.intervalTool.isVisibleProperty
  inputEnabledProperty
  -handle1
    inputEnabledProperty
    visibleProperty
    +dragListener
  -handle2
    inputEnabledProperty
    visibleProperty
    +dragListener
  -intervalRectangle
    inputEnabledProperty
    +dragListener
```

**Comment by marlitas** [comment] 2023-09-13 18:57
Changes have been implemented in the above commits. The studio tree doesn't exactly match @pixelzoom's recommendation since we decided to not instrument the inputEnabled Properties of each handle in a previous design meeting, but we may want to change that now? 

Sending over to @catherinecarter to review the studio tree since there were significant changes with how the IntervalTool displays in both the view and model.

This is also ready for @Nancy-Salpepi to test on main. 

As well as... a code review. Sending over to @pixelzoom since he originally looked into and proposed the fix.

**Comment by Nancy-Salpepi** [comment] 2023-09-13 23:21
`model.intervalToolModel.isTranslationEnabledProperty` is working nicely in main!

**Comment by catherinecarter** [comment] 2023-09-15 17:27
Agreed! Looks great.

**Comment by pixelzoom** [comment] 2023-09-18 20:56
The revised implementation of IntervalToolNode and its associate Studio subtree looks very nice. Well done.

Back to @marlitas in case there's anything else to do here. Feel free to close.

**Comment by marlitas** [comment] 2023-09-18 21:38
Awesome. I think we can close this. Thanks all!

**Closed by marlitas** 2023-09-18 21:38 UTC
Labels: type:bug, dev:phet-io, status:ready-for-review
