### ISSUE TITLE
Create the PhET-iO Examples

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#136] opened 2022-04-22 20:09 UTC
A bit late, but for https://github.com/phetsims/qa/issues/798. Noticed during a more recent phet-io test.

In studio there are two links (PhET-iO Guide, and Examples) that don't lead to anything. These links are on the right hand side of Studio.

**Comment by amanda-phet** [comment] 2023-04-20 22:23
My guess is that these don't work because we didn't create this documentation! @catherinecarter will probably be the one to do that when this sim gets published :)

**Comment by catherinecarter** [comment] 2023-06-22 21:10
Making a checklist of things to remember to include in examples.md:

All screens
- [ ] change size of variability for distribution of kicks
- [ ] Get and set an array of balls to be placed (magically without kicking) at specific locations on the number line
   - [ ] two types of arrays: one has 15 places in it, and the user sets the number of balls at each of the 15 locations on the number line. Second is to list the positions of each kick and what number line value for where you want the ball to land
- [ ] Choose from a list of pre-set frequency distributions: skewed right/left, unimodal and symmetric (large/small spread), uniform, top hat, bimodal
   - [ ] note: these are frequency distributions. the probabilities are calculated in the code
- [ ] Customize the name of the screens, the accordion box labels, and the question at the top
- [ ] Customize checkbox labels
- [ ] Visible and enabled properties on all checkboxes, the accordion box, the question, the balls on the whole, each individual ball
- [ ] Accordion box will shift upwards when the question bar is hidden
- [ ] Change location of cueing arrow on balls (all screens)

Median Screen
- [ ] Can listen to an indicator telling whether the cards (Median screen) have been sorted or not
- [ ] Change location of the cueing arrow to move the cards
- [ ] Set the location of the predict median slider
- [ ] Be able to hide a card on Median Screen

Mean & Median Screen
- [ ] Visible and enabled properties for the mean/median indicators
- [ ] Set the location of the predict sliders (mean/median)
- [ ] Be able to hide the data points in the accordion box

Variability Screen
- [ ] hide the drag handles of the interval tool, one or both
- [ ] get the location of each handle of the interval tool (if width is desired, encourage client to calculate)
- [ ] visible/enabled properties for one or more radio buttons for measures of spread
- [ ] visible/enabled properties for info button
- [ ] set distribution for each player
- [ ] visible/enabled properties for number line/data points in accordion box while allowing a graph to appear
- [ ] create/set a measure of spread (range, boxplot, MAD) prior to kicking 
- [ ] be able to hide the data points in the accordion box

**Comment by samreid** [comment] 2023-08-08 16:22
To show the card hand drag indicator `centerAndVariability.medianScreen.model.distanceAccordionBox.cardContainerModel.cardDragIndicatorProperty` 'setValue` 

```{
  "phetioID": "centerAndVariability.medianScreen.model.distanceAccordionBox.cardContainerModel.cards.card1"
}
```

**Comment by catherinecarter** [comment] 2023-08-30 14:57
@arouinfar checked the examples file, and confirmed all looks good. Closing.

**Closed by catherinecarter** 2023-08-30 14:57 UTC
Labels: design:phet-io
