### ISSUE TITLE
Interval tool sounds

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#236] opened 2023-06-02 16:53 UTC
On Wednesday, May 31, the sound team had a meeting and discussed sounds for the interval tool and the spread rectangles showing the measures of spread. Here's a summary of the conversation about how to add sound to these tools, with invitations for feedback prior to our next meeting:

1. The handles of the interval tool have sounds similar to the predict mean/median but subtly different from each other so a user could distinguish between touching one handle over the other.
   - [ ] What positive/negative impacts can you think of for having the left and right handles have subtly different sounds, if any?

2. An idea was to add sound to both the interval tool and the spread rectangles in the accordion box to indicate two things:
- position on the number line (higher pitch to indicate a higher number)
- width of the rectangles (a longer note to indicate a wider interval)
   - [ ] What ideas do you have / impacts can you foresee with the position/width having a similar sound as the number line sound (currently indicates both position of ball landing and the prediction mean/median tools)
   - [ ] If the interval tool is translated (i.e. the width is constant but the position is changing), what ideas are out there to distinguish the position changing while the width doesn't, keeping in mind the tool will be moving so the length of the sound would need to be held constant?

Note: the spread rectangle sounds in the accordion box would only play when the checkbox would be toggled on.

**Comment by emily-phet** [comment] 2023-06-04 13:45
@Ashton-Morris 
Here's a description of the sound design we came up with for the interval tool, on the third screen of Center and Variability. 

When the Interval Tool is enabled, two knobs appear with a highlighted box between them. We want to emphasize the width of this box (the interval!), more than the location of a knob on the number line as you interact. So the mapping of the sound would be to the width of the interval. Notice, that you can move the leftmost knob up to and past the rightmost knob (and vice versa). 

One sound, maybe a continuous one, that changes in pitch as you move the knobs making width of the interval bigger or smaller. When you release, a discrete sound mapped to the width of the interval, ringing out longer for wider interval. (longest duration would still need to be quite short, we don't want people feeling like they need to wait for the sound to end. This same discrete sound could also be used for discrete interactions with the interval tool - e.g., keyboard navigation.

Note: I wonder if it would be useful to have two variants of this sound, subtly different in timbre, so that one is associated with the movement the left knob and the other associated with the right knob. This might be too much, but if you have ideas for this, please make a demo. Again, I'm thinking something so subtly different, maybe 40% of people wouldn't even notice it (like a light filter on the first sound to create the second sound...just so people who are really attending deeply to the sound notice and can distinguish between them).

Next, the whole interval can be shifted to lie in different locations along the number line, the width stays fixed but the whole box can be moved. Here we don't need to indicate the width during movement, but the location. So a sound that changes in pitch as you move along the number line. Not sure if this should be continuous or discrete - probably discrete to match other mappings to the number line. 

Does this make sense? Can you make a demo of some/all of these for Tuesday's meeting?

**Comment by emily-phet** [comment] 2023-06-04 13:47
Note - I think this is something we should just hear a demo of, and decide steps from there, so unassigning everyone but @Ashton-Morris. 

Just like artwork, it's often most efficient to experience a demo (like seeing a sketch) rather than discussing at length something we're all trying to imagine in our minds. Especially if there are multiple sounds / mappings involved.

**Comment by Ashton-Morris** [comment] 2023-06-08 18:45
Here are some mapping and Sonification notes for the interval tool handles. @samreid 

Take a look at the code for our continuous [sound in GFL:B](https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics_all.html)
 
I believe the audio we are using is called **saturatedSineLoopTrimmed** and JB has some code in there which helps it loop better. I think the mapping could be the same to how what you showcased in the last meeting with the web audio sine. 

As for differentiating the handles I think you should start with a band pass filter on handle 2 and see if that sounds slightly different enough. If that sounds weird then maybe trying a low pass filter would work also. 

GFL:B should have all of the information you need to do a looping sound from an audio file.

**Comment by matthew-blackman** [comment] 2023-06-15 15:48
During a design check-in with @catherinecarter, she confirmed the desired audio design:

- Dragging the entire interval area should play a continuous sound for the width of the tool, independent of where it is.
- The sound on the grab/release should fade out faster.

**Comment by matthew-blackman** [comment] 2023-06-15 16:23
@catherinecarter ready for design review!

**Comment by catherinecarter** [comment] 2023-06-15 16:38
I think it's great! I'd like to take to the sound design team before calling it closed to see what they think about the fade length. I still think it could be a bit shorter, but want to know what @Ashton-Morris, @emily-phet, and @kathy-phet think as well. Thanks!

**Comment by emily-phet** [comment] 2023-06-15 22:04
@catherinecarter - The basics of this seem great to me. Continuous sound changing in pitch as the knobs are moved and each knob has a slightly different variant of the sound. 

I agree the duration of sound could drop faster on release. Right now it feels slightly unresponsive or inconsistent as you interact and I wonder if this all would be addressed with more rapid fade of the sound. 

It feels good with alternative input as well. Though, I notice there's no way to move the entire interval window (at least, none that I could find) with alternative input. Given it's possible to create a window anywhere by moving the knobs individually, this is probably ok.

**Comment by Ashton-Morris** [comment] 2023-06-21 13:20
I think the mapping sounds good in general. I agree with above that it sounds a bit out of place so I will try to find some other looping sounds to test.

Also I can hear it repeating each time the loop ends causing a clicking or heartbeat kind of sound which we should continue to try to minimize.

**Comment by samreid** [comment] 2023-06-21 19:22
After we fine tune that audio, we will likely adjust the fade timeout.

We would also like to investigate the thresholded approach in https://github.com/phetsims/center-and-variability/issues/236#issuecomment-1584554673

**Comment by samreid** [comment] 2023-06-21 23:11
To test the thresholded approach, please launch with `?intervalToolSoundInterval=0.05` and keep in mind it only applies when the width changes.  I'm not sure if we will like it or not (or even if I like it or not). @catherinecarter and @emily-phet and @Ashton-Morris can you please test?  If we like it, we could apply a similar "pulsing" approach to when translating the interval tool.  Here's a link for testing: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet&intervalToolSoundInterval=0.05

**Comment by catherinecarter** [comment] 2023-06-22 17:04
The fade sounds great to me now.

I heard a double sound when dragging either one of the handles or translating the interval when my mouse would move, say, 1 pixel without me knowing I moved. This happened upon releasing my mouse.

In terms of this change (from above: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet&intervalToolSoundInterval=0.05), I think this is nice. The incremental changes in sound help make the connection between the width and the pitch.

This issue will be closed now that there are many specific things to keep track of at this point. This issue will be broken into four issues to address the 
- adjustment of the sound quality
- width indicator (?intervalToolSoundInterval=0.05)
- pick up/drop of a handle (double sound)
- translation sound of the entire interval (pulse or no pulse)

**Comment by Ashton-Morris** [comment] 2023-06-22 18:35
I am adding these sounds I created to test as alternative loops. They are in our normal folder and I have included .wav files as well incase we want to hear it loop seamlessly for testing as we work on the .mp3 looping.

**cvIntervalToolLoopSoundV1.wav
cvIntervalToolLoopSoundV3.mp3
cvIntervalToolLoopSoundV3.wav
cvIntervalToolLoopSoundV2.mp3
cvIntervalToolLoopSoundV2.wav
cvIntervalToolLoopSoundV1.mp3**

Also I added these sounds which we used in My Solar System if anyone thinks they may fit. 

- cvBodiesStringse3.mp3
- cvBodiesOrganb3.mp3
- cvBodiesFluteg3.mp3
- cvBodiesBrassc3.mp3
- cvBodiesBrassc3.wav
- cvBodiesOrganb3.wav
- cvBodiesFluteg3.wav
- cvBodiesStringse3.wav

Lastly I attached one that we used for a tool in Waves Intro 

- cvWaveMeterSawTone.mp3

**Comment by Ashton-Morris** [comment] 2023-06-22 18:39
> To test the thresholded approach, please launch with `?intervalToolSoundInterval=0.05` and keep in mind it only applies when the width changes. I'm not sure if we will like it or not (or even if I like it or not). @catherinecarter and @emily-phet and @Ashton-Morris can you please test? If we like it, we could apply a similar "pulsing" approach to when translating the interval tool. Here's a link for testing: https://bayes.colorado.edu/dev/phettest/center-and-variability/center-and-variability_en.html?ea&brand=phet&intervalToolSoundInterval=0.05

I think this sounds good.

**Comment by phet-dev** [comment] 2023-06-23 09:40
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment] 2023-06-23 12:49
Thanks @phet-dev, I moved the TODO accordingly, closing.

**Closed by samreid** 2023-06-23 12:49 UTC
Labels: design:sound, dev:sound
