### ISSUE TITLE
PhET-iO needs for March 30th (if possible) 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-variability#105] opened 2022-03-23 16:49 UTC
- [x] global control for making balls not pickable/draggable 
- [x] hide any UI controls (checkboxes, buttons, accordion boxes) 
- [x] get value from prediction arrows 
- [x] get value of mean
- [x] get value of median 

I believe some of these can already be checked, but leaving the complete list here so QA can test this when all of these capabilities are ready.

**Comment by chrisklus** [comment] 2022-03-23 17:01
@Nancy-Salpepi here is what should be tested in Studio - I don't believe the first request exists yet, so @samreid and I will have to add that next week. I'm not sure if the second one is complete, so that would be helpful to know. And hopefully the last three are good to go.

Tagging https://github.com/phetsims/qa/issues/789

**Comment by Nancy-Salpepi** [comment] 2022-03-24 19:48
@chrisklus For #2 on the list, I don't see visibleProperty for any of the checkboxes on either screen.

**Comment by Nancy-Salpepi** [comment] 2022-03-24 23:46
@amanda-phet did you want individual control for the kick buttons? Currently there is only one visible property for the group: `view.kickButtonGroup.visibleProperty`.

**Comment by Nancy-Salpepi** [comment] 2022-03-25 00:35
@chrisklus  I don't see the `get value`, `set value`, `copy set value code` options for Mean and Median on either screen. 
<img width="583" alt="Screen Shot 2022-03-24 at 8 27 45 PM" src="https://user-images.githubusercontent.com/87318828/160031647-656f5cea-8797-4f56-9d43-b39e9b572f5e.png">

**Comment by KatieWoe** [comment] 2022-03-28 20:24
If there is a way to do 1 I haven't found it yet. Let me know if I'm missing something obvious but I can't seem to find this control, either in Featured or All.

**Comment by Nancy-Salpepi** [comment] 2022-03-28 20:26
The first doesn't exist yet. See https://github.com/phetsims/center-and-variability/issues/105#issuecomment-1076576977

**Comment by KatieWoe** [comment] 2022-03-28 20:28
Ahh, sorry about that. Thanks for pointing it out.

**Comment by samreid** [comment] 2022-03-29 16:48
We renamed eraserButton => eraseButton more like a verb, like the reset all button.

**Comment by samreid** [comment] 2022-03-29 17:42
> I don't see the get value, set value, copy set value code options for Mean and Median on either screen.

Those options are not available for items marked as "read only".  We don't want to allow PhET-iO users to override the mean or median, since it should be derived from the model values.  There are controls to change the contributing values (ball locations) within the sim.

We added the kick button visibleProperty, added a pickableProperty for the soccer ball group, instrumented all the checkboxes.

@Nancy-Salpepi @KatieWoe @amanda-phet can you please review?  If all is well, please relabel for cherry-picking.

**Comment by Nancy-Salpepi** [comment] 2022-03-29 18:38
@samreid @chrisklus  I have a question about the property `view.topCheckboxGroup.sortDataCheckbox.enabledProperty`

If I check the Sort Data checkbox, disable that checkbox and then launch the sim, the box will become unchecked once I move a card (and can't recheck it unless I press reset all). So should we be able to disable this property?

**Comment by Nancy-Salpepi** [comment] 2022-03-29 20:32
When testing `view.soccerBallNodeGroup.pickableProperty` on the Mean and Median Screen, an error came up. After refreshing Master, I was not able to reproduce, but noting anyway. 
<img width="1162" alt="Screen Shot 2022-03-29 at 4 18 42 PM" src="https://user-images.githubusercontent.com/87318828/160701772-cbe11832-66ff-4a2a-ba05-2ff95699e849.png">

**Comment by kathy-phet** [comment] 2022-03-29 21:16
@samreid @chrisklus - I don't think we use pickable property any more. I thought we used inputEnabledProperty. e.g, 
phScale.macroScreen.view.pHMeterNode.probeNode.inputEnabledProperty

@arouinfar - Can you comment?

**Comment by arouinfar** [comment] 2022-03-29 21:25
>I don't think we use pickable property any more. I thought we used inputEnabledProperty. e.g,
phScale.macroScreen.view.pHMeterNode.probeNode.inputEnabledProperty
>
> @arouinfar - Can you comment?

We deprecated `pickableProperty` in favor of `inputEnabledProperty` in https://github.com/phetsims/scenery/issues/1158.  While I am fairly certain that "pickable" is still a thing found in the code, it's not something we should be exposing in the Studio tree. If a Node needs to be uninteractive without appearing to be disabled, it should have an `inputEnabledProperty`.

**Comment by samreid** [comment] 2022-03-30 15:44
> @samreid @chrisklus I have a question about the property view.topCheckboxGroup.sortDataCheckbox.enabledProperty
> 
> If I check the Sort Data checkbox, disable that checkbox and then launch the sim, the box will become unchecked once I move a card (and can't recheck it unless I press reset all). So should we be able to disable this property?

@chrisklus and I reproduced this behavior, and discussed it.  It seems plausible that a client may want the checkbox to serve as a readout of whether the data is sorted, so disabling it may be reasonable in that case.

**Comment by samreid** [comment] 2022-03-30 15:55
@chrisklus and I switched to use inputEnabledProperty instead of pickableProperty and opened a new issue about forbidding that tandem name in general.  We weren't able to reproduce the problem described in https://github.com/phetsims/center-and-variability/issues/105#issuecomment-1082346338, so this issue is ready for review.  @amanda-phet can you please review and mark for cherry-picking if it seems good?

**Comment by amanda-phet** [comment] 2022-03-30 20:18
I confirmed the following locations for achieving what I listed: 

- `centerAndVariability.medianScreen.view.soccerBallNodeGroup.inputEnabledProperty`
- `centerAndVariability.medianScreen.view.topCheckboxGroup.sortDataCheckbox.visibleProperty`
- `centerAndVariability.medianScreen.view.topCheckboxGroup.medianCheckbox.visibleProperty`
- `centerAndVariability.medianScreen.view.bottomCheckboxGroup.predictMedianCheckbox.visibleProperty`
- `centerAndVariability.meanAndMedianScreen.view.resetAllButton.visibleProperty`
- `centerAndVariability.medianScreen.view.eraseButton.visibleProperty`
- `centerAndVariability.medianScreen.view.kickButtonGroup.kickFiveButton.visibleProperty`
- `centerAndVariability.medianScreen.view.kickButtonGroup.kickOneButton.visibleProperty`
- `centerAndVariability.medianScreen.view.bottomCheckboxGroup.medianCheckbox`
- `centerAndVariability.medianScreen.model.medianPredictionProperty`
- `centerAndVariability.medianScreen.model.meanValueProperty`
- `centerAndVariability.medianScreen.model.medianValueProperty`

And likewise on the Mean & Median screen: 
- `centerAndVariability.meanAndMedianScreen.view.resetAllButton.visibleProperty`
- `centerAndVariability.meanAndMedianScreen.view.eraseButton.visibleProperty`
- `centerAndVariability.meanAndMedianScreen.view.kickButtonGroup.kickOneButton.visibleProperty`
- `centerAndVariability.meanAndMedianScreen.view.kickButtonGroup.kickFiveButton.visibleProperty`
- `centerAndVariability.meanAndMedianScreen.model.medianPredictionProperty`
- `centerAndVariability.meanAndMedianScreen.model.meanPredictionProperty`
- `centerAndVariability.meanAndMedianScreen.model.meanValueProperty`
- `centerAndVariability.meanAndMedianScreen.model.medianValueProperty`

I didn't list every single ID, just the ones I want to reference later. Ready for cherry-picking!

**Comment by chrisklus** [comment] 2022-04-06 18:31
@samreid and I spot-checked this for https://github.com/phetsims/center-and-variability/issues/122, closing.

**Closed by chrisklus** 2022-04-06 18:31 UTC
Labels: design:phet-io, dev:phet-io, status:ready-to-cherry-pick
