### ISSUE TITLE
Long hold on kick button leads to multiple clicks

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#102] opened 2022-03-22 22:29 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/789
If you hold the "Kick 1" button down for a moment, more than one kick will happen, and it will continue after you let go.

**Visuals**
![longclick](https://user-images.githubusercontent.com/41024075/159586662-775d6bae-dd31-4578-a6e5-1cfa17f909e5.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Variability‬
URL: https://phet-dev.colorado.edu/html/center-and-variability/1.0.0-rc.1/phet/center-and-variability_all_phet.html
Version: 1.0.0-rc.1 2022-03-21 16:46:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment] 2022-03-23 15:59
I think the bug here is that only 5 kicks should have happened in this case, because the mouse was released and kicks continued to occur.

**Comment by chrisklus** [comment] 2022-03-28 19:38
@samreid and I thought about a fix for this and came up with two ideas:

1. Cancel the remaining queued kicks when the user releases holding down the "Kick 1" button.
2. Match the fire-on-hold rate of the "Kick 1" button to the rate of the multi-kick "release" for when soccer balls are in the queue.

We think 2 will be simplest to try out first.

**Comment by samreid** [comment] 2022-03-28 23:06
@KatieWoe can you please review the proposal in phettest?  If it seems OK, please relabel as "ready for cherry pick".

**Comment by KatieWoe** [comment] 2022-03-29 16:01
I found this behavior much, much better. My only note is that "Kick 5" does not behave the same way, and only fires when you let go. Is this intended?

**Comment by chrisklus** [comment] 2022-03-29 18:55
Thanks @KatieWoe! Yes, fire-on-hold is intentionally disabled for "Kick 5".

**Comment by samreid** [comment] 2022-04-06 18:43
@chrisklus and I confirmed this is fixed in in https://github.com/phetsims/center-and-variability/issues/122, closing.

**Closed by samreid** 2022-04-06 18:43 UTC
Labels: type:bug, status:ready-to-cherry-pick
